services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-monitoring
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      # :ro means only read only permission
      - ./secrets/token.txt:/etc/secrets/token.txt:ro
    env_file:
      - .env